// <auto-generated />
namespace WebSuiBeauty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcustommer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcustommer1));
        
        string IMigrationMetadata.Id
        {
            get { return "202305150234405_add-custommer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
